name = "contactswap-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
API_APP_URL = "https://contactswap-api.quinten.dev"
FRONTEND_APP_URL = "https://contactswap.quinten.dev"
DEFAULT_API_SECRET = "contactswap"
MAILERSEND_EMAIL_FROM = "no-reply@test-zxk54v8nooqljy6v.mlsender.net"
MAILERSEND_ENABLED = "true"

[dev]
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "D1"
database_name = "contactswap-db"
database_id = "d24dd0b0-c385-4309-82e2-d07f1a519f0d"

[[r2_buckets]]
binding = "R2"
bucket_name = "contactswap-files"

[triggers]
crons = [ "0 3 * * *" ]

[env.production]
name = "contactswap-api"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = false

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
